### ISSUE TITLE
Problem building

### ISSUE THREAD

**Issue by JensNordenbro** [localmed/diversion#8]
When building I get a lot of build errors. 

Basically it all ends up in projects having dependencies to Diversion.MSBuild-nuget not at nuget.org. 

When trying to build only Diversion.MsBuild assembly I got the following: 

> 2>------ Build started: Project: Diversion.Reflection, Configuration: Debug Any CPU ------
> 2>D:\git\github\diversion\Diversion.Reflection\Diversion.Reflection.csproj : error NU1101: Unable to find package Diversion.MSBuild. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, Nuget.org
> 2>Done building project "Diversion.Reflection.csproj" -- FAILED.
> 3>------ Build started: Project: Diversion.MSBuild, Configuration: Debug Any CPU ------
> 3>CSC : error CS0006: Metadata file 'D:\git\github\diversion\Diversion\bin\Debug\net462\Diversion.dll' could not be found
> 3>CSC : error CS0006: Metadata file 'D:\git\github\diversion\Diversion.Reflection\bin\Debug\net462\Diversion.Reflection.dll' could not be found
> 3>Done building project "Diversion.MSBuild.csproj" -- FAILED.
> ========== Build: 0 succeeded, 3 failed, 0 up-to-date, 0 skipped ==========
> 

Is there a cyclic dependency between Diversion.MsBuild and Diversion.Reflection? 
Also it is strange that there is a nuget dependency and still Diversion.MsBuild is included in the sources.. 

Please enlighten me on how to get started!

**Comment by michaelmelancon** [comment]
I apologize for that, the self referential stuff will not work until Diversion.MSBuild has been published to a feed you have access to. I removed the self referential code from master. I am working on a branch that leverages the Deterministic flag and reworks the CLI and MSBuild clients for better compatibility, but it is a bit of a work in progress. I work on it when I have time between other things.

**Comment by JensNordenbro** [comment]
ok,  thanks! Would it be possible to evaluate a binary in the meantime?
